In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def max_norm_cross_corr(x1, x2):
    
    correlation= normalized_cross_corr(x1, x2)
    
    lag = abs(correlation).argmax() - len(x1)+1
    
    max_corr = max(abs(correlation))
    
    return(max_corr, lag)
    
def normalized_cross_corr(x,y):
    x_mean = np.mean(x)
    y_mean = np.mean(y)
    
    x_cov_std = np.nanmax(np.sqrt(np.correlate(x - x_mean, x - x_mean, 'full')))
    y_cov_std = np.nanmax(np.sqrt(np.correlate(y - y_mean, y - y_mean, 'full')))

    normalization = x_cov_std * y_cov_std
        

    unnormalized_correlation = np.correlate(x - x_mean, y - y_mean, 'full')
    
    corr_array = unnormalized_correlation/normalization

    return(corr_array)

def cross_correlation_matrix(data):
    #input: n x t matrix where n is the number of rois and t is the duration of the time series
    #return: n x n cross correlation matrix and lag matrix
    n, t = data.shape
    X = np.zeros((n,n))
    lag = np.zeros((n,n))
    
    for i in range(n-1):
        for j in range(i+1,n):
            X[i][j],lag[i][j] = max_norm_cross_corr(data[i,:],data[j,:])
    X[np.isnan(X)] = 0
    lag[np.isnan(lag)] = 0
    
    X = X + X.T
    lag = lag + lag.T
    return(X,lag)

In [32]:
a = np.array([[0,0,0,1,1,0,1,0,1,0,0,1,1,0,1],[1,1,0,0,1,1,1,0,1,0,0,1,1,1,1],[1,1,0,0,1,1,1,0,1,0,0,1,1,1,1]])
b = np.array([[0.4,0.23,.32,.12,.85,.43],[.32,.12,0,0,.45,.9],[.32,.12,0,0,.45,1]])
c = np.array([[1,0,0.3],[0.2,0.2,0.2],[1,0,1],[0.2,0.2,0.2],[.21,0,0]])
#b = np.array([1,1,0,0,1,1,1,0,1,0,0,1,1,1,1])
#max_norm_cross_corr(a,b)

In [33]:
#cross_correlation_matrix(a)
#cross_correlation_matrix(b)
cross_correlation_matrix(c)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in sqrt
  from ipykernel import kernelapp as app
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in sqrt
  app.launch_new_instance()


(array([[0.        , 0.45081579, 0.88131886, 0.45081579, 0.95632472],
        [0.45081579, 0.        , 0.23570226, 1.        , 0.47140452],
        [0.88131886, 0.23570226, 0.        , 0.23570226, 0.83333333],
        [0.45081579, 1.        , 0.23570226, 0.        , 0.47140452],
        [0.95632472, 0.47140452, 0.83333333, 0.47140452, 0.        ]]),
 array([[ 0., -2., -1., -2.,  0.],
        [-2.,  0., -2.,  0.,  2.],
        [-1., -2.,  0., -2.,  1.],
        [-2.,  0., -2.,  0.,  2.],
        [ 0.,  2.,  1.,  2.,  0.]]))

In [16]:
c.shape
c[2,:]

array([0.2, 0.2])